### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by achereshnevdg** [marsson/dataDicGen#2]
I have this error whenever I'm trying to run the command. Happy to dive into debugging on my machine

MacOS 10.14.6 (18G103)
sfdx-cli/7.168.0 darwin-x64 node-v16.17.0
sfdxdatadicgen 0.1.2

<img width="515" alt="Screenshot 2022-09-21 at 16 42 33" src="https://user-images.githubusercontent.com/111866229/191535220-473de0f8-afcd-40e4-b842-b6a084571980.png">

**Comment by marsson** [comment]
Sorry for the delay in replying.
I have updated the versions of the dependencies. Can you update to the current version and try again?

**Comment by achereshnevdg** [comment]
@marsson, no worries!
It worked.
